apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myadmin-hpa
  namespace: myadmin-dev
  labels:
    app.kubernetes.io/name: myadmin-hpa
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: myadmin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myadmin-api
  minReplicas: 3 # Minimum number of pods to maintain during the crash test
  maxReplicas: 10 # Maximum number of pods to scale up to during the crash test
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Target average CPU utilization percentage for scaling. If the average CPU usage across all pods exceeds this value, the HPA will scale up the number of pods.
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70 # Target average memory utilization percentage for scaling.
  behavior:
    scaleUp:
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15 # Not to scale up more than 100% every 15 seconds to avoid overreaction
    scaleDown:
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15 # Not to scale down more than 100% every 15 seconds to avoid overreaction
      stabilizationWindowSeconds: 300 # Wait 5 minutes before reducing pods to avoid oscillations