apiVersion: apps/v1
kind: Deployment
metadata:
  name: myadmin-deployment
  namespace: default
  labels:
    app: myadmin
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myadmin
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      imagePullSecrets:
      - name: gar-credentials
      containers:
      - name: myadmin-core
        image: us-west1-docker.pkg.dev/myadminproject-497120/myadmin-repo/myadmin-app:IMAGE_TAG
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "200m"
        imagePullPolicy: IfNotPresent
        env: 
          # Injection des variables requises par l'application Python
          - name: ENV
            value: "production"
          - name: DATABASE_URL
            # Utilisation du nom du service K3s comme hôte
            value: "mysql+pymysql://myadmin_user:MyAdminUserProd@myadmin-db-service:3306/myadmin_db"

          # Récupération des secrets depuis Kubernetes
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: myadmin-api-secrets
                key: secret-key
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: myadmin-api-secrets
                key: encryption-key
---
apiVersion: v1
kind: Service
metadata:
  name: myadmin-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80         # Le port exposé par le service K3s aux autres composants (ex: Ingress)
    targetPort: 8000 # Redirige proprement vers le port 8000 du conteneur Python
  selector:
    app: myadmin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myadmin-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myadmin-service
            port:
              number: 80 # Rejoint le service sur son port 80