---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myadmin-api
  namespace: myadmin-dev
  labels:
    app.kubernetes.io/name: myadmin-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: myadmin
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: myadmin-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myadmin-api
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: myadmin
    spec:
      imagePullSecrets:
        - name: gar-credentials
      containers:
        - name: myadmin-core
          # yamllint disable-line rule:line-length
          image: us-west1-docker.pkg.dev/myadminproject-497120/myadmin-repo/myadmin-app:IMAGE_TAG
          ports:
            - containerPort: 8000
              name: http-api
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "200m"
          imagePullPolicy: IfNotPresent
          env:
            # Inject the ENV variable to differentiate environments
            - name: ENV
              value: "development"
            # Retrieve secrets from Kubernetes
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-production-secrets
                  key: db-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: myadmin-api-secrets
                  key: secret-key
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: myadmin-api-secrets
                  key: encryption-key
---
apiVersion: v1
kind: Service
metadata:
  name: myadmin-api-service
  namespace: myadmin-dev
  labels:
    app.kubernetes.io/name: myadmin-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: myadmin
spec:
  type: ClusterIP
  ports:
    # Expose on port 80 for a clean redirect from the Ingress
    - port: 80
      # Corresponds to the port name defined in the container
      targetPort: http-api
      # Port name for a clear reference in the Ingress
      name: http
  selector:
    app.kubernetes.io/name: myadmin-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myadmin-api-ingress
  namespace: myadmin-dev
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/name: myadmin-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: myadmin
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myadmin-api-service
                port:
                  name: http
