apiVersion: v1
kind: Secret
metadata:
  name: myadmin-api-secrets
  namespace: myadmin-dev
  labels:
    app.kubernetes.io/name: myadmin-api-secrets
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: myadmin
type: Opaque
stringData:
  secret-key: "998c4116ca491a080bc02f86403d6a9a301039baa0b1b92141c4c705786c8dee"
  encryption-key: "KHXh9WB5-vUI8A79LQNYULrbKgoNu0qKMyq8iRvjLfc="
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-production-secrets
  namespace: myadmin-dev
  labels:
    app.kubernetes.io/name: mysql-production-secrets
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: myadmin
type: Opaque
stringData:
  mysql-root-password: "PasswordRootProd" # To be modified
  mysql-password: "MyAdminUserProd"       # To be modified
  mysql-user: "myadmin_user"             # To be modified if needed
  mysql-database: "myadmin_db"           # To be modified if needed
  # It follows the format: mysql+pymysql://<user>:<password>@<service-name>:<port>/<database-name>.
  db-url: "mysql+pymysql://myadmin_user:MyAdminUserProd@myadmin-db-service:3306/myadmin_db" # To be modified if needed