apiVersion: v1
kind: Secret
metadata:
  name: myadmin-api-secrets
  namespace: default
type: Opaque
stringData:
  secret-key: "998c4116ca491a080bc02f86403d6a9a301039baa0b1b92141c4c705786c8dee"
  encryption-key: "KHXh9WB5-vUI8A79LQNYULrbKgoNu0qKMyq8iRvjLfc="
