apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: myadmin-vpa
  namespace: myadmin-dev
  labels:
    app.kubernetes.io/name: myadmin-vpa
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: myadmin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myadmin-api
  updatePolicy:
    updateMode: "Off" # This allows for manual control over resource allocation, ensuring that changes are deliberate and tested before being applied to the deployment.
  resourcePolicy:
    containerPolicies:
    - containerName: "myadmin-core" # This allows for fine-grained control over resource allocation for specific containers, rather than applying a blanket policy to all containers in the pod.
      minAllowed:
        cpu: "100m"
        memory: "128Mi"
      maxAllowed:
        cpu: "1"
        memory: "1Gi"